/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package openBook.api

import openBook.model.BookGetByInfoIdResponse
import openBook.model.BookGetByNameResponse
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired


import kotlinx.coroutines.flow.Flow
import kotlin.collections.List
import kotlin.collections.Map

@RequestMapping("\${api.base-path:}")
interface BookApi {


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/v1/book/find-by-name/{book_name}"],
            produces = ["application/json"]
    )
    suspend fun v1BookFindByNameBookNameGet( @PathVariable("book_name") bookName: kotlin.String): ResponseEntity<BookGetByNameResponse>


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/v1/book/get-by-info/{book_info_id}"],
            produces = ["application/json"]
    )
    suspend fun v1BookGetByInfoBookInfoIdGet( @PathVariable("book_info_id") bookInfoId: java.util.UUID): ResponseEntity<BookGetByInfoIdResponse>
}
