openapi: 3.0.3
info:
  title: api
  description: api
  version: 1.0.0
paths:
  /v1/reserve:
    post:
      tags:
        - Booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './responses.yaml#/components/schemas/BookReserveResponse'
