openapi: 3.0.3
info:
  title: api
  description: api
  version: 1.0.0
paths:
  /v1/reserve:
    post:
      tags:
        - Booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './api.yaml#/components/schemas/BookReservationId'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './responses.yaml#/components/schemas/BookReserveResponse'
        404:
          description: NOT FOUND
          content:
            application/json:
              schema:
                $ref: '../../core-search/spec/responses.yaml#/components/schemas/ErrorResponse'

components:
  schemas:
    BookReservationId:
      type: object
      required:
        - book_id
      properties:
        book_id:
          type: string
          format: uuid
