openapi: 3.0.3
info:
  title: server responses
  description: server responses
  version: 1.0.0
paths: { }

components:
  schemas:
    BookReserveResponse:
      type: object
      required:
        - reserved_date
        - reservation_expiration_date
      properties:
        reserved_date:
          type: string
          format: date-time
        reservation_expiration_date:
          type: string
          format: date-time

    BookReservationDetailsResponse:
      type: object
      required:
        - reserved_date
        - reservation_expiration_date
        - book_id
      properties:
        book_id:
          type: string
          format: uuid
        reserved_date:
          type: string
          format: date-time
        reservation_expiration_date:
          type: string
          format: date-time