openapi: 3.0.3
info:
  title: server definitions
  description: server definitions
  version: 1.0.0
paths: { }

components:
  schemas:
    BookInfo:
      type: object
      required:
        - id
        - name
        - authorId
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          description: name of a book
        authorId:
          type: string
          format: uuid
          description: foreign key to a book's author

    Book:
      type: object
      required:
        - id
        - publisherId
        - libraryId
        - bookInfoId
        - status
      properties:
        id:
          type: string
          format: uuid
        bookInfoId:
          type: string
          format: uuid
        publisherId:
          type: string
          format: uuid
          description: key to a book publication id
        libraryId:
          type: string
          format: uuid
          description: library this is in
        status:
          $ref: '#/components/schemas/BookStatus'

    BookStatus:
      type: string
      enum:
        - AVAILABLE
        - UNAVAILABLE
      default: 'UNAVAILABLE'