spring:
  application:
    name: core-catalog-writer
  r2dbc:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

server:
  port: 8083