server:
  port: 8080

external:
  core-booking:
    url: ${CORE_BOOKING_URL}
  core-catalog:
    url: ${CORE_CATALOG_URL}
  core-catalog-writer:
    url: ${CORE_CATALOG_WRITER_URL}
  core-search:
    url: ${CORE_SEARCH_URL}

spring:
  security:
    authorities:
      client: CLIENT
      library: LIBRARY
      moderator: MODERATOR
  r2dbc:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem