openapi: 3.0.3
info:
  title: OpenBook
  description: OpenBook
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'

paths:
  /v1/book/get-info/{book_id}:
    get:
      parameters:
        - in: path
          name: book_id
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/BookInfoResponse'
        400:
          $ref: './responses.yaml#/components/responses/400'
        404:
          $ref: './responses.yaml#/components/responses/404'
        500:
          $ref: './responses.yaml#/components/responses/500'

  /v1/author/get-info/{author_id}:
    get:
      parameters:
        - in: path
          name: author_id
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/AuthorInfoResponse'
        400:
          $ref: './responses.yaml#/components/responses/400'
        404:
          $ref: './responses.yaml#/components/responses/404'
        500:
          $ref: './responses.yaml#/components/responses/500'

  /v1/library/get-info/{library_id}:
    get:
      parameters:
        - in: path
          name: library_id
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/LibraryInfoResponse'
        400:
          $ref: './responses.yaml#/components/responses/400'
        404:
          $ref: './responses.yaml#/components/responses/404'
        500:
          $ref: './responses.yaml#/components/responses/500'
