openapi: 3.0.3
info:
  title: OpenBook
  description: OpenBook
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'

paths:
  /v1/book/get/{book_id}:
    get:
      parameters:
        - in: path
          name: book_id
          required: true
          schema:
            $ref: './components.yaml#/components/schemas/BookId'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/BookResponse'
        304:
          description: Not modified
        400:
          $ref: './responses.yaml#/components/responses/400'
        404:
          $ref: './responses.yaml#/components/responses/404'
        500:
          $ref: './responses.yaml#/components/responses/500'

  /v1/book/add:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/BookAddRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/BookResponse'
        304:
          description: Not modified
        400:
          $ref: './responses.yaml#/components/responses/400'
        500:
          $ref: './responses.yaml#/components/responses/500'

  /v1/author/get/{author_id}:
    get:
      parameters:
        - in: path
          name: author_id
          required: true
          schema:
            $ref: './components.yaml#/components/schemas/AuthorId'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/AuthorResponse'
        304:
          description: Not modified
        400:
          $ref: './responses.yaml#/components/responses/400'
        404:
          $ref: './responses.yaml#/components/responses/404'
        500:
          $ref: './responses.yaml#/components/responses/500'

  /v1/author/add:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/AuthorAddRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/AuthorResponse'
        304:
          description: Not modified
        400:
          $ref: './responses.yaml#/components/responses/400'
        500:
          $ref: './responses.yaml#/components/responses/500'

  /v1/library/get/{library_id}:
    get:
      parameters:
        - in: path
          name: library_id
          required: true
          schema:
            $ref: './components.yaml#/components/schemas/LibraryId'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/LibraryResponse'
        304:
          description: Not modified
        400:
          $ref: './responses.yaml#/components/responses/400'
        404:
          $ref: './responses.yaml#/components/responses/404'
        500:
          $ref: './responses.yaml#/components/responses/500'

  /v1/library/add:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/LibraryAddRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/AuthorResponse'
        304:
          description: Not modified
        400:
          $ref: './responses.yaml#/components/responses/400'
        500:
          $ref: './responses.yaml#/components/responses/500'
