openapi: 3.0.3
info:
  title: OpenBook
  description: OpenBook
  version: 1.0.0

paths:
  /v1/book/find-by-name/{book_name}:
    get:
      tags:
        - Book
      parameters:
        - in: path
          name: book_name
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/BookGetByNameResponse'
        404:
          $ref: './responses.yaml#/components/responses/404'

  /v1/book/get-by-info/{book_info_id}:
    get:
      tags:
        - Book
      parameters:
        - in: path
          name: book_info_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/BookGetByInfoIdResponse'
        404:
          $ref: './responses.yaml#/components/responses/404'

  /v1/book/reservation:
    post:
      tags:
        - Book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - book_id
              properties:
                book_id:
                  type: string
                  format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/BookReserveResponse'

  /v1/author/details/{author_id}:
    get:
      tags:
        - Author
      parameters:
        - in: path
          name: author_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/AuthorDetailsResponse'
        404:
          $ref: './responses.yaml#/components/responses/404'

  /v1/library/details/{library_id}:
    get:
      tags:
        - Library
      parameters:
        - in: path
          name: library_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/LibraryDetailsResponse'
        404:
          $ref: './responses.yaml#/components/responses/404'