openapi: 3.0.3
info:
  title: http responses
  description: http responses
  version: 1.0.0
paths: {}

components:
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OkResponse'
    404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundResponse'

  schemas:
    OkResponse:
      type: object
      properties:
        data:
          type: string
          description: OK

    BadRequestResponse:
      type: object
      properties:
        error:
          type: string
          description: Bad request

    NotFoundResponse:
      type: object
      required:
        - errorMessage
      properties:
        errorMessage:
          type: string
          description: Object not found

    InternalErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Internal Server Error
