spring:
  application:
    name: core-openbook
    reservation_expiration_time: 2419200000 #week
  datasource:
    url: jdbc:postgresql://localhost:5432/openbook
    username: postgres
    password: 31p6hd19
