/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package openBook.api

import openBook.model.BookGetByInfoIdResponse
import openBook.model.BookInfo
import openBook.model.BookReserveResponse
import openBook.model.NotFoundResponse
import openBook.model.V1BookReservationPostRequest
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired


import kotlin.collections.List
import kotlin.collections.Map

@RequestMapping("\${api.base-path:}")
interface BookApi {


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/v1/book/find-by-name/{book_name}"],
            produces = ["application/json"]
    )
    fun v1BookFindByNameBookNameGet( @PathVariable("book_name") bookName: kotlin.String): ResponseEntity<List<BookInfo>>


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/v1/book/get-by-info/{book_info_id}"],
            produces = ["application/json"]
    )
    fun v1BookGetByInfoBookInfoIdGet( @PathVariable("book_info_id") bookInfoId: java.util.UUID): ResponseEntity<BookGetByInfoIdResponse>


    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/v1/book/reservation"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun v1BookReservationPost( @RequestBody v1BookReservationPostRequest: V1BookReservationPostRequest): ResponseEntity<BookReserveResponse>
}
