/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package openBook.api

import openBook.model.BookReservationDetailsResponse
import openBook.model.BookReservationId
import openBook.model.BookReserveResponse
import openBook.model.ErrorResponse
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired


import kotlinx.coroutines.flow.Flow
import kotlin.collections.List
import kotlin.collections.Map

@RequestMapping("\${api.base-path:}")
interface BookingApi {


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/v1/reservation/{book_id}"],
            produces = ["application/json"]
    )
    suspend fun v1ReservationBookIdGet( @PathVariable("book_id") bookId: java.util.UUID): ResponseEntity<BookReservationDetailsResponse>


    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/v1/reserve"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    suspend fun v1ReservePost( @RequestBody bookReservationId: BookReservationId): ResponseEntity<BookReserveResponse>
}
